import preact from '@preact/preset-vite'
import { type Plugin, defineConfig, loadEnv } from 'vite'

/**
 * The security headers both sites serve, differing only in which API each one
 * is allowed to reach.
 *
 * Generated rather than kept as a file in public/, because public/ is copied
 * into both builds — one shared _headers meant the back office and the
 * storefront had to agree on a single connect-src, and the only value that
 * satisfies both is the union of what either needs. Deriving it from the same
 * env the client reads keeps the policy and the code from disagreeing.
 *
 * Two deliberate loosenings:
 *   'unsafe-inline' in style-src — progress and statistics bars set their
 *     width through a style attribute, which this covers.
 *   static.cloudflareinsights.com — Cloudflare injects its analytics beacon
 *     into pages on this zone.
 */
export function contentSecurityPolicy(apiOrigin: string, imageOrigin: string): string {
  return [
    "default-src 'self'",
    "script-src 'self' https://static.cloudflareinsights.com",
    "style-src 'self' 'unsafe-inline'",
    // Product photos and bio-link avatars are served by the public API for
    // both sites, so this one does not vary.
    `img-src 'self' ${imageOrigin} data:`,
    `connect-src 'self' ${apiOrigin} https://static.cloudflareinsights.com`,
    "font-src 'self'",
    "object-src 'none'",
    "base-uri 'none'",
    // No form on either site posts anywhere. When the PAYUNi payment form
    // arrives it submits cross-origin, and this is the line that will have to
    // name that host rather than being widened to 'self'.
    "form-action 'none'",
    "frame-ancestors 'none'",
  ].join('; ')
}

function securityHeaders(apiOrigin: string, imageOrigin: string): Plugin {
  const body = [
    '# Generated by vite.config.ts. Do not edit the built copy.',
    '/*',
    '  X-Frame-Options: DENY',
    '  Referrer-Policy: no-referrer',
    '  X-Content-Type-Options: nosniff',
    `  Content-Security-Policy: ${contentSecurityPolicy(apiOrigin, imageOrigin)}`,
    '',
  ].join('\n')

  return {
    name: 'luma-security-headers',
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: '_headers', source: body })
    },
  }
}

/**
 * Serve admin.html as the dev shell when running the back office.
 *
 * `rollupOptions.input` only steers a build. The dev server answers a
 * navigation with index.html whatever the mode, so without this
 * `npm run dev:admin` quietly serves the storefront on the back office's port
 * — the mode swaps the env vars and nothing else, which is a confusing way to
 * spend an afternoon.
 */
function adminDevShell(): Plugin {
  return {
    name: 'luma-admin-dev-shell',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use((request, _response, next) => {
        // Navigations only. Module and asset requests do not ask for HTML,
        // and rewriting those would break the dev client.
        if (request.headers.accept?.includes('text/html')) request.url = '/admin.html'
        next()
      })
    },
  }
}

/**
 * Two sites out of one project.
 *
 * The storefront and the back office are separate deployments on separate
 * hostnames, but they share components, types and the API client, so they
 * stay one npm project with one dependency tree. `--mode admin` swaps the
 * HTML entry and the output directory; everything else is identical.
 *
 * Vite names an emitted HTML file after its source, so the admin build's
 * shell lands at dist/admin/admin.html rather than index.html. Its Worker
 * knows that; see the SHELL constant in worker/admin.ts.
 */
export default defineConfig(({ mode }) => {
  const admin = mode === 'admin'
  const env = loadEnv(mode, process.cwd(), 'VITE_')
  const apiOrigin = env.VITE_API_BASE || 'https://api.luma-studio.tw'
  const imageOrigin = env.VITE_PUBLIC_API_BASE || 'https://api.luma-studio.tw'

  return {
    plugins: [preact(), securityHeaders(apiOrigin, imageOrigin), ...(admin ? [adminDevShell()] : [])],
    build: {
      outDir: admin ? 'dist/admin' : 'dist/storefront',
      // No sourcemaps in the deployed bundle: they are three times the size of
      // the code and publish the original source to anyone who opens devtools.
      sourcemap: false,
      emptyOutDir: true,
      rollupOptions: { input: { index: admin ? 'admin.html' : 'index.html' } },
    },
    server: { port: admin ? 5174 : 5173, strictPort: true },
  }
})
